spring:
  application:
    name: executor
  rabbitmq:
    host: localhost
    port: 5672
    stream:
      username: guest
      password: guest
  data:
    mongodb:
      authentication-database: admin
      database: testContainer
      port: 27017
server:
  port: 8080