spring:
  application:
    name: executor
  rabbitmq:
    host: localhost
    port: 5672
    stream:
      username: guest
      password: guest
  data:
    mongodb:
      uri: mongodb+srv://kieuviet34_db_user:kieuviet2004@learningapp.jqpx9hf.mongodb.net/testContainer
server:
  port: 8080